# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='opened', max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('recipients', models.TextField(blank=True, null=True)),
                ('uuid', models.CharField(blank=True, default=uuid.uuid1, max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Email'),
        ),
    ]
