# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='from_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='reply_to',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
