# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20170911_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ('-send_date',)},
        ),
        migrations.AddField(
            model_name='email',
            name='send_now',
            field=models.BooleanField(default=True),
        ),
    ]
