# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20170912_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='number_sent',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
