# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_email_number_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='uuid',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
