# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20170914_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='from_address',
        ),
        migrations.AddField(
            model_name='email',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
