# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20170914_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(blank=True, default='open', max_length=50),
        ),
    ]
