# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-13 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20170914_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='number_recipients',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
